# Jekyll 配置参数

name: 暮语的角落
description: '在工作中的一些记录，整理的同时，也是整理一下自己'

# Url is currently only used only for the RSS feed in feed.xml
url: https://GuoSongyu.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

# 分享设置
share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: false
# 底部图标链接设置
social:
  github: GuoSongyu
  RSS: feed.xml

# cnzz Web流量统计
cnzz_key: true
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
#yandex_metrica:
#标签页面标题设置
tag_title_prefix: 标签分类 "
tag_title_suffix: 

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
#disqus: streetturtle
#comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
